// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmOJlivp9Cj19LAkB0f1cqHZBArS5TpUo',
    appId: '1:969632208542:web:a957f3a2b453e5d82c8d8f',
    messagingSenderId: '969632208542',
    projectId: 'challenges-2f0c5',
    authDomain: 'challenges-2f0c5.firebaseapp.com',
    storageBucket: 'challenges-2f0c5.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMcGIh2TtyRyVJrejrcZJZWrumzfKEzgY',
    appId: '1:969632208542:ios:3219303e8413c6102c8d8f',
    messagingSenderId: '969632208542',
    projectId: 'challenges-2f0c5',
    storageBucket: 'challenges-2f0c5.appspot.com',
    iosBundleId: 'com.example.challengeUrMemory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmOJlivp9Cj19LAkB0f1cqHZBArS5TpUo',
    appId: '1:969632208542:web:8a49b8d7c4aa9add2c8d8f',
    messagingSenderId: '969632208542',
    projectId: 'challenges-2f0c5',
    authDomain: 'challenges-2f0c5.firebaseapp.com',
    storageBucket: 'challenges-2f0c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMcGIh2TtyRyVJrejrcZJZWrumzfKEzgY',
    appId: '1:969632208542:ios:3219303e8413c6102c8d8f',
    messagingSenderId: '969632208542',
    projectId: 'challenges-2f0c5',
    storageBucket: 'challenges-2f0c5.appspot.com',
    iosBundleId: 'com.example.challengeUrMemory',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrvqiufcDouxI507NuoYVjbXWLXZ5OIQI',
    appId: '1:969632208542:android:bdf3d41adf3de2932c8d8f',
    messagingSenderId: '969632208542',
    projectId: 'challenges-2f0c5',
    storageBucket: 'challenges-2f0c5.appspot.com',
  );

}